export interface ICourses{
        id:number,
        title:string,
        time?:string,
        shortDescription:string,
        fullDescription:string,
        language?:string,
        Category?:string,
        duration?:string,
        instructor?:string,
        price:number,
        days?:string[],
        lessonsCount:number,
        level:"Beginner" | "Intermediate"|"Advanced",
}
export const Courses:ICourses[] = [
    {
        id:1,
        title:"Ill Manors",
        time:"18:00",
        shortDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        language:"En",
        price:60,
        days:["Sun", "Tue"],
        duration:"4 Weeks",
        Category:"Frontend",
        lessonsCount:3,
        instructor:"Elzero",
        level:"Beginner",
       fullDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi sapiente eveniet possimus suscipit eos iusto aperiam voluptatum rem. Odio magni molestias praesentium dignissimos pariatur consectetur dicta adipisci cupiditate repellendus in!"
    },
     {
        id:1,
        title:"Ill Manors",
        time:"18:00",
        shortDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        language:"En",
        price:60,
        days:["Sun", "Tue"],
        duration:"4 Weeks",
        Category:"Frontend",
        lessonsCount:3,
        instructor:"Elzero",
        level:"Beginner",
       fullDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi sapiente eveniet possimus suscipit eos iusto aperiam voluptatum rem. Odio magni molestias praesentium dignissimos pariatur consectetur dicta adipisci cupiditate repellendus in!"
    },
      {
        id:1,
        title:"Ill Manors",
        time:"18:00",
        shortDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        language:"En",
        price:60,
        days:["Sun", "Tue"],
        duration:"4 Weeks",
        Category:"Frontend",
        lessonsCount:3,
        instructor:"Elzero",
        level:"Beginner",
       fullDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi sapiente eveniet possimus suscipit eos iusto aperiam voluptatum rem. Odio magni molestias praesentium dignissimos pariatur consectetur dicta adipisci cupiditate repellendus in!"
    },
    {
        id:1,
        title:"Ill Manors",
        time:"18:00",
        shortDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        language:"En",
        price:60,
        days:["Sun", "Tue"],
        duration:"4 Weeks",
        Category:"Frontend",
        lessonsCount:3,
        instructor:"Elzero",
        level:"Beginner",
       fullDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi sapiente eveniet possimus suscipit eos iusto aperiam voluptatum rem. Odio magni molestias praesentium dignissimos pariatur consectetur dicta adipisci cupiditate repellendus in!"
    },
    
     {
        id:1,
        title:"Ill Manors",
        time:"18:00",
        shortDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        language:"En",
        price:60,
        days:["Sun", "Tue"],
        duration:"4 Weeks",
        Category:"Frontend",
        lessonsCount:3,
        instructor:"Elzero",
        level:"Beginner",
       fullDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi sapiente eveniet possimus suscipit eos iusto aperiam voluptatum rem. Odio magni molestias praesentium dignissimos pariatur consectetur dicta adipisci cupiditate repellendus in!"
    },
      {
        id:1,
        title:"Ill Manors",
        time:"18:00",
        shortDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        language:"En",
        price:60,
        days:["Sun", "Tue"],
        duration:"4 Weeks",
        Category:"Frontend",
        lessonsCount:3,
        instructor:"Elzero",
        level:"Beginner",
       fullDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi sapiente eveniet possimus suscipit eos iusto aperiam voluptatum rem. Odio magni molestias praesentium dignissimos pariatur consectetur dicta adipisci cupiditate repellendus in!"
    },
      {
        id:1,
        title:"Ill Manors",
        time:"18:00",
        shortDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        language:"En",
        price:60,
        days:["Sun", "Tue"],
        duration:"4 Weeks",
        Category:"Frontend",
        lessonsCount:3,
        instructor:"Elzero",
        level:"Beginner",
       fullDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi sapiente eveniet possimus suscipit eos iusto aperiam voluptatum rem. Odio magni molestias praesentium dignissimos pariatur consectetur dicta adipisci cupiditate repellendus in!"
    },
     {
        id:1,
        title:"Ill Manors",
        time:"18:00",
        shortDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        language:"En",
        price:60,
        days:["Sun", "Tue"],
        duration:"4 Weeks",
        Category:"Frontend",
        lessonsCount:3,
        instructor:"Elzero",
        level:"Beginner",
       fullDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi sapiente eveniet possimus suscipit eos iusto aperiam voluptatum rem. Odio magni molestias praesentium dignissimos pariatur consectetur dicta adipisci cupiditate repellendus in!"
    },
    {
        id:1,
        title:"Ill Manors",
        time:"18:00",
        shortDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        language:"En",
        price:60,
        days:["Sun", "Tue"],
        duration:"4 Weeks",
        Category:"Frontend",
        lessonsCount:3,
        instructor:"Elzero",
        level:"Beginner",
       fullDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi sapiente eveniet possimus suscipit eos iusto aperiam voluptatum rem. Odio magni molestias praesentium dignissimos pariatur consectetur dicta adipisci cupiditate repellendus in!"
    },
    {
        id:1,
        title:"Ill Manors",
        time:"18:00",
        shortDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        language:"En",
        price:60,
        days:["Sun", "Tue"],
        duration:"4 Weeks",
        Category:"Frontend",
        lessonsCount:3,
        instructor:"Elzero",
        level:"Beginner",
       fullDescription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi sapiente eveniet possimus suscipit eos iusto aperiam voluptatum rem. Odio magni molestias praesentium dignissimos pariatur consectetur dicta adipisci cupiditate repellendus in!"
    },
]